'use client';
import React,{useEffect,useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import {records,SourceRecord,categories,countryCentres,catalogYears,timeMatches} from '../catalogue';
import type {UfoCase} from '../MapComponent';
const Map=dynamic(()=>import('../MapComponent'),{ssr:false,loading:()=> <p>Načítám mapu…</p>});
const initial={q:'',release:'',agency:'',kind:'',country:'',category:'',from:'',to:'',clockFrom:'',clockTo:'',dateKind:'',ready:''};
type Reading={dossier?:{overview_cs:string;context_cs:string;findings:{text_cs:string;source_units:string[]}[]}; units:{unit_key:string;timestamp_seconds?:number;parts:{summary_cs:string;context_cs:string;translation_cs:string;limitations_cs:string[]}[]}[]};
export default function Catalogue(){
 const [filters,setFilters]=useState(initial),[selected,setSelected]=useState<string>(records[0]?.source_id||''),[mode,setMode]=useState('seznam');
 const [reading,setReading]=useState<Reading|null>(null),[readingError,setReadingError]=useState(''),[activeAnalysis,setActiveAnalysis]=useState(0),[page,setPage]=useState(1);
 const set=(key:keyof typeof initial,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(1)};
 const countries=useMemo(()=>[...new Set(records.map(r=>r.translation?.country_cs).filter(Boolean))].sort() as string[],[]);
 const filtered=useMemo(()=>records.filter(r=>{
  const f=filters,t=r.translation,ys=catalogYears(r);
  if(f.release&&r.release!==f.release||f.agency&&r.agency!==f.agency||f.kind&&r.document_type!==f.kind||f.category&&t?.category!==f.category||f.dateKind&&t?.date_kind!==f.dateKind)return false;
  if(f.ready==='yes'&&!r.analyses?.length||f.ready==='no'&&r.analyses?.length)return false;
  const inYears=(y:number|null)=>y!==null&&(!f.from||y>=Number(f.from))&&(!f.to||y<=Number(f.to));
  if(f.clockFrom||f.clockTo){if(!r.events?.some(e=>timeMatches(e.time_local,f.clockFrom,f.clockTo)&&(!f.country||e.country_cs===f.country)&&(!(f.from||f.to)||inYears(e.year))))return false;}
  else{if(f.country&&(f.country==='unknown'?!!t?.country_cs:t?.country_cs!==f.country))return false;if((f.from||f.to)&&!ys.some(inYears))return false;}
  return !f.q||[r.asset_file_name,r.description_en,t?.title_cs,t?.description_cs,r.incident_location,...r.local_filenames].join(' ').toLocaleLowerCase('cs').includes(f.q.toLocaleLowerCase('cs'));
 }),[filters]);
 const current=filtered.find(r=>r.source_id===selected)||filtered[0];
 useEffect(()=>{setActiveAnalysis(0)},[current?.source_id]);
 useEffect(()=>{let cancelled=false;setReading(null);setReadingError('');const url=current?.analyses?.[activeAnalysis]?.url;if(url)fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()}).then(r=>{if(!cancelled)setReading(r)}).catch(()=>{if(!cancelled)setReadingError('Uložený rozbor se nepodařilo načíst. Zkuste obnovit stránku.')});return()=>{cancelled=true}},[current?.source_id,activeAnalysis]);
 const mapCases=filtered.filter(r=>r.translation?.category==='pozorovani'&&countryCentres[r.translation?.country_cs||'']).map(r=>({id:r.source_id,title:r.translation?.title_cs||r.asset_file_name,date:r.incident_date,location:'Orientační střed země: '+r.translation?.country_cs,latitude:countryCentres[r.translation!.country_cs!][0],longitude:countryCentres[r.translation!.country_cs!][1]} as UfoCase));
 const timeline=[...new Set(filtered.flatMap(catalogYears))].sort((a,b)=>a-b);
 const choose=(r:SourceRecord)=>{setSelected(r.source_id);setActiveAnalysis(0)};
 const select=(key:keyof typeof initial,label:string,options:[string,string][])=> <label className="text-sm text-slate-300">{label}<select aria-label={label} className="block bg-slate-900 border border-slate-600 rounded p-2 mt-1 w-full" value={filters[key]} onChange={e=>set(key,e.target.value)}><option value="">Vše</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;
 return <main className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8">
  <header className="max-w-screen-2xl mx-auto mb-6"><a href="/" className="text-cyan-300 text-sm">← Původní analytický přehled</a><h1 className="text-3xl font-bold mt-3">UAP · Český archiv pramenů</h1><p className="text-slate-300 mt-2">Vládní popisy česky, uložené rozbory a přímé odkazy na originály. Média zůstávají na vládním webu.</p><p className="text-sm text-slate-400 mt-2">{records.length} archivních záznamů · šest várek · metadata získána 24. 9. 2026. Jeden záznam nemusí znamenat jedno samostatné pozorování.</p></header>
  <section aria-label="Filtry katalogu" className="max-w-screen-2xl mx-auto rounded-xl border border-slate-700 bg-slate-900/70 p-4">
   <label className="block mb-3">Hledat v názvu, popisu a názvu souboru<input type="search" value={filters.q} onChange={e=>set('q',e.target.value)} placeholder="Například Tremonton, AAWSAP nebo Colorado…" className="block w-full rounded bg-slate-950 border border-slate-600 p-3 mt-1"/></label>
   <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-3">
    {select('release','Várka',['01','02','03','04','05','06'].map(x=>[x,'Release '+x]))}
    {select('kind','Typ média',[...new Set(records.map(r=>r.document_type))].sort().map(x=>[x,x==='VID'?'Video':x==='AUD'?'Audio':x==='IMG'?'Obrázek':x]))}
    {select('category','Povaha materiálu',Object.entries(categories))}
    {select('country','Země / území',[...countries.map(x=>[x,x] as [string,string]),['unknown','Neurčeno / více zemí']])}
    {select('agency','Agentura',[...new Set(records.map(r=>r.agency))].sort().map(x=>[x,x]))}
    {select('ready','Podrobný český rozbor',[['yes','Alespoň část připravena'],['no','Zatím nepřipraven']])}
    <label className="text-sm text-slate-300">Rok od<input aria-label="Rok od" type="number" min="1" max="9999" value={filters.from} onChange={e=>set('from',e.target.value)} className="block w-full bg-slate-900 border border-slate-600 rounded p-2 mt-1"/></label>
    <label className="text-sm text-slate-300">Rok do<input aria-label="Rok do" type="number" min="1" max="9999" value={filters.to} onChange={e=>set('to',e.target.value)} className="block w-full bg-slate-900 border border-slate-600 rounded p-2 mt-1"/></label>
    {select('dateKind','Význam katalogového data',[['pozorovani','Datum pozorování'],['dokument','Datum dokumentu'],['neurceno','Význam nejistý']])}
    <label className="text-sm text-slate-300">Čas ve zdroji od<input type="time" value={filters.clockFrom} onInput={e=>set('clockFrom',e.currentTarget.value)} onChange={e=>set('clockFrom',e.target.value)} className="block w-full bg-slate-900 border border-slate-600 rounded p-2 mt-1"/></label>
    <label className="text-sm text-slate-300">Čas ve zdroji do<input type="time" value={filters.clockTo} onInput={e=>set('clockTo',e.currentTarget.value)} onChange={e=>set('clockTo',e.target.value)} className="block w-full bg-slate-900 border border-slate-600 rounded p-2 mt-1"/></label>
    <button className="border border-slate-500 rounded self-end p-2" onClick={()=>{setFilters(initial);setPage(1)}}>Zrušit filtry</button>
   </div><p className="text-xs text-slate-400 mt-3">Roky vycházejí z katalogového data; filtr významu data odděluje dokumenty od pozorování. Časový filtr používá pouze doložené údaje z hotových rozborů, bez převodu pásem. Klasifikace a přiřazení země jsou strojové.</p>
  </section>
  <div className="max-w-screen-2xl mx-auto flex gap-2 items-center flex-wrap my-4"><strong role="status" className="mr-auto">{filtered.length} {filtered.length===1?'záznam':filtered.length>=2&&filtered.length<=4?'záznamy':'záznamů'}</strong>{[['seznam','Seznam'],['mapa','Mapa světa'],['osa','Časová osa']].map(([value,label])=><button key={value} aria-pressed={mode===value} className={'px-4 py-2 rounded '+(mode===value?'bg-cyan-700':'bg-slate-800')} onClick={()=>setMode(value)}>{label}</button>)}</div>
  {mode==='mapa'&&<section className="max-w-screen-2xl mx-auto mb-5"><p className="text-sm text-amber-200 mb-2">Mapa seskupuje {mapCases.length} záznamů pozorování podle země. Body označují orientační středy zemí, nikoli přesná místa událostí. Záznamy bez jednoznačné země se nezobrazují. Kliknutím otevřete výběr záznamů dané země.</p><div className="h-96 rounded-xl overflow-hidden"><Map cases={Object.keys(countryCentres).flatMap(country=>{const group=mapCases.filter(c=>c.location==='Orientační střed země: '+country);return group.length?[{...group[0],id:country,title:country+' · '+group.length+' záznamů'}]:[]})} onMarkerClick={c=>set('country',String(c.id))}/></div></section>}
  {mode==='osa'&&<section aria-label="Časová osa" className="max-w-screen-2xl mx-auto mb-5 p-4 bg-slate-900 rounded-xl"><h2 className="text-lg font-bold">Časová osa katalogových dat</h2><p className="text-sm text-slate-400 mb-3">Víceleté záznamy se mohou objevit u více roků. Bez známého roku: {filtered.filter(r=>!catalogYears(r).length).length}.</p><div className="flex flex-wrap gap-2">{timeline.map(y=><button key={y} onClick={()=>{setFilters(f=>({...f,from:String(y),to:String(y)}));setPage(1)}} className="bg-slate-800 border border-slate-600 p-2 rounded">{y} <span className="text-cyan-300">({filtered.filter(r=>catalogYears(r).includes(y)).length})</span></button>)}</div></section>}
  <div className="max-w-screen-2xl mx-auto grid lg:grid-cols-[340px_minmax(0,1fr)] gap-5">
   <aside aria-label="Výsledky hledání" className="lg:max-h-[85vh] overflow-auto"><div className="flex justify-between mb-3"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Zpět</button><span>{page} / {Math.max(1,Math.ceil(filtered.length/30))}</span><button disabled={page*30>=filtered.length} onClick={()=>setPage(p=>p+1)}>Další →</button></div>{filtered.slice((page-1)*30,page*30).map(r=><button key={r.source_id} onClick={()=>choose(r)} className={'block text-left w-full p-4 mb-2 rounded-lg border '+(r.source_id===current?.source_id?'bg-cyan-950 border-cyan-400':'bg-slate-900 border-slate-700')}><small className="text-cyan-300">R{r.release} · {r.document_type} · {r.incident_date||'Datum neuvedeno'}</small><h2 className="font-semibold mt-1">{r.translation?.title_cs||r.asset_file_name}</h2><p className="text-xs text-slate-400 mt-2">{categories[r.translation?.category||'']||'Dosud nezařazeno'}{r.analyses?.length?' · Rozbor připraven':''}</p></button>)}</aside>
   {!current?<p>Žádný záznam neodpovídá filtrům. Zkuste rozšířit výběr.</p>:<article className="bg-slate-900 border border-slate-700 rounded-xl p-5 md:p-7 min-w-0">
    <p className="text-cyan-300 text-sm">Release {current.release} · {current.agency}</p><h2 className="text-2xl font-bold my-3">{current.translation?.title_cs||current.asset_file_name}</h2>
    <div className="flex flex-wrap gap-3 mb-5"><a className="bg-cyan-700 hover:bg-cyan-600 rounded px-4 py-3 font-semibold" href={current.source_url} target="_blank" rel="noopener noreferrer">Otevřít originální záznam ↗</a>{current.download_url&&current.document_type==='PDF'&&<a className="border border-slate-500 rounded px-4 py-3" href={current.download_url} target="_blank" rel="noopener noreferrer">Originální PDF ↗</a>}</div>
    <dl className="grid sm:grid-cols-2 gap-3 bg-slate-950 rounded p-4 text-sm"><div><dt className="text-slate-400">Datum v katalogu ({current.translation?.date_kind==='pozorovani'?'pozorování':current.translation?.date_kind==='dokument'?'dokument':'význam nejistý'})</dt><dd>{current.incident_date||'Neuvedeno'}</dd></div><div><dt className="text-slate-400">Místo podle katalogu</dt><dd>{current.translation?.location_cs||current.incident_location||'Neuvedeno'}</dd></div></dl>
    <h3 className="text-xl font-semibold mt-6 mb-3">Co o materiálu uvádí vládní katalog</h3><p className="text-sm text-amber-200 mb-3">Český strojový překlad popisu vydavatele. Nejde o nezávislé potvrzení jeho závěrů ani o překlad celého souboru.</p><div className="whitespace-pre-wrap leading-7">{current.translation?.description_cs||'Český překlad katalogového popisu zatím není připraven.'}</div>
    <details className="mt-5 border-t border-slate-700 pt-3"><summary className="cursor-pointer text-cyan-300">Původní anglický popis a identifikace</summary><p className="my-3 font-mono text-xs break-words">{current.asset_file_name}</p><p className="whitespace-pre-wrap text-slate-300 leading-7">{current.description_en}</p><p className="mt-3 text-xs">Místní soubory: {current.local_filenames.join(', ')||'Párování dosud neověřeno'}</p></details>
    {!!current.related_ids.length&&<section className="mt-6"><h3 className="font-semibold">Související materiály podle vydavatele</h3><div className="flex flex-wrap gap-2 mt-2">{current.related_ids.map(id=>{const related=records.find(r=>r.asset_file_name.startsWith(id+','));return related?<button key={id} className="text-cyan-300 border border-slate-600 rounded p-2" onClick={()=>{setFilters(initial);setSelected(related.source_id);setPage(Math.floor(records.indexOf(related)/30)+1)}}>{id}</button>:<span key={id}>{id}</span>})}</div></section>}
    <section className="mt-7 border-t border-slate-700 pt-5"><h3 className="text-xl font-semibold">Podrobný český rozbor souboru</h3>{!current.analyses?.length?<p className="mt-3 text-slate-300">Tento soubor zatím nemá připravený podrobný překlad nebo obrazový rozbor. Výše si již můžete přečíst český popis vydavatele a jedním kliknutím otevřít originál.</p>:<><p className="my-3 text-amber-200 text-sm">Strojové zpracování bez odborné revize. U videa se rozbor týká pouze vybraných snímků, nikoli celého pohybu a zvuku.</p>{current.analyses.length>1&&<select aria-label="Verze místního souboru" value={activeAnalysis} onChange={e=>setActiveAnalysis(Number(e.target.value))}>{current.analyses.map((a,i)=><option key={a.sha256} value={i}>Soubor {i+1} · {a.units} částí</option>)}</select>}{readingError?<p role="alert">{readingError}</p>:!reading?<p>Načítám uložený rozbor…</p>:<>{reading.dossier&&<div className="my-4 leading-7"><p>{reading.dossier.overview_cs}</p><p className="text-slate-300 mt-3">{reading.dossier.context_cs}</p></div>}{reading.units.map(u=><details key={u.unit_key} className="border border-slate-700 rounded p-4 my-3"><summary className="cursor-pointer font-semibold">{u.unit_key.startsWith('page:')?'Strana '+u.unit_key.split(':')[1]:'Snímek '+(u.timestamp_seconds??u.unit_key)+' s'}</summary>{u.parts.map((p,i)=><div key={i} className="leading-7 mt-4"><h4 className="font-bold">Shrnutí</h4><p>{p.summary_cs}</p><p className="mt-3 text-slate-300">{p.context_cs}</p><h4 className="font-bold mt-4">České čtení</h4><p className="whitespace-pre-wrap">{p.translation_cs}</p>{p.limitations_cs.map((l,j)=><p key={j} className="text-amber-200 mt-2 text-sm">{l}</p>)}</div>)}</details>)}</>}</>}</section>
   </article>}
  </div>
 </main>;
}
